//@ui5-bundle cristian/lasttry/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"cristian/lasttry/Component.js":function(){sap.ui.define(["sap/fe/core/AppComponent"],function(t){"use strict";return t.extend("cristian.lasttry.Component",{metadata:{manifest:"json"}})});
},
	"cristian/lasttry/i18n/i18n.properties":'# This is the resource bundle for cristian.lasttry\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=lasttry\n\n#YDES: Application description\nappDescription=A Fiori application.\n\nflpTitle=lastTRY\n\nflpSubtitle=\n',
	"cristian/lasttry/manifest.json":'{"_version":"1.58.0","sap.app":{"id":"cristian.lasttry","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:lrop","version":"1.11.2","toolsId":"70b4e9fc-7e24-400c-a31f-9e38347b773d"},"dataSources":{"mainService":{"uri":"collection-manger/","type":"OData","settings":{"annotations":[],"localUri":"localService/metadata.xml","odataVersion":"4.0"}}},"crossNavigation":{"inbounds":{"lastTRY-display":{"semanticObject":"lastTRY","action":"display","title":"{{flpTitle}}","subTitle":"{{flpSubtitle}}","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.119.1","libs":{"sap.m":{},"sap.ui.core":{},"sap.ushell":{},"sap.fe.templates":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"cristian.lasttry.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true}},"@i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"}},"resources":{"css":[]},"routing":{"config":{},"routes":[{"pattern":":?query:","name":"ToyCarsList","target":"ToyCarsList"},{"pattern":"ToyCars({key}):?query:","name":"ToyCarsObjectPage","target":"ToyCarsObjectPage"}],"targets":{"ToyCarsList":{"type":"Component","id":"ToyCarsList","name":"sap.fe.templates.ListReport","options":{"settings":{"contextPath":"/ToyCars","variantManagement":"Page","navigation":{"ToyCars":{"detail":{"route":"ToyCarsObjectPage"}}}}}},"ToyCarsObjectPage":{"type":"Component","id":"ToyCarsObjectPage","name":"sap.fe.templates.ObjectPage","options":{"settings":{"editableHeaderContent":false,"contextPath":"/ToyCars"}}}}}},"sap.fiori":{"registrationIds":[],"archeType":"transactional"},"sap.cloud":{"public":true,"service":"lastTry"}}'
}});
